### ISSUE TITLE
cannot install using command on Zorin, ubuntu based

### ISSUE THREAD

**Issue by quenyan** [mrossini-ethz/gimp-wavelet-denoise#4]
sudo make
make -C po
make[1]: Entering directory '/home/tentram/gimp-wavelet-denoise-master/po'
msgfmt -c -v -o de.mo de.po
36 translated messages.
msgfmt -c -v -o ru.mo ru.po
36 translated messages.
msgfmt -c -v -o it.mo it.po
36 translated messages.
msgfmt -c -v -o et.mo et.po
36 translated messages.
msgfmt -c -v -o pl.mo pl.po
36 translated messages.
msgfmt -c -v -o sr.mo sr.po
36 translated messages.
msgfmt -c -v -o sr@latin.mo sr@latin.po
36 translated messages.
make[1]: Leaving directory '/home/tentram/gimp-wavelet-denoise-master/po'
make -C src
make[1]: Entering directory '/home/tentram/gimp-wavelet-denoise-master/src'
Package lcms2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lcms2.pc'
to the PKG_CONFIG_PATH environment variable
Package 'lcms2', required by 'babl', not found
No output from 'pkg-config --cflags gimpui-2.0'
cc -O3 -ldl -Wall  -c -o plugin.o plugin.c
In file included from plugin.c:16:0:
plugin.h:21:10: fatal error: libgimp/gimp.h: No such file or directory
 #include <libgimp/gimp.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by quenyan** [comment]
Any other easier installer like .Deb file or something? I've been really bad with make install thingy.

**Comment by mrossini-ethz** [comment]
Hi quenyan

It seems that you are doing everything right. Problem is, the packages

- 'libcms2-dev'
- 'libgimp2.0-dev'

appear to be missing on your system. (These are Ubuntu package names.)

If you are using Ubuntu, then you may want to install the package

- 'gimp-plugin-registry'

which contains the denoise plugin. Then you don't have to compile anything.

Cheers

**Comment by quenyan** [comment]
omg....thank you so so so much for your nice reply. This is solved my problem right away. You're a life-saver. (thumbs up)

**Comment by mrossini-ethz** [comment]
Thanks!
